// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbiWb0fNXs1eARfwM22pxRHNhqU63B56A',
    appId: '1:761898792675:web:98a8a1044cbd1830db77d6',
    messagingSenderId: '761898792675',
    projectId: 'flavor-sample-app-prod',
    authDomain: 'flavor-sample-app-prod.firebaseapp.com',
    storageBucket: 'flavor-sample-app-prod.firebasestorage.app',
    measurementId: 'G-KR4Q3Z87C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXugga_I5obD0_IQz7B1dnnPPkHfcBg9w',
    appId: '1:761898792675:android:3de2201231bc3a7edb77d6',
    messagingSenderId: '761898792675',
    projectId: 'flavor-sample-app-prod',
    storageBucket: 'flavor-sample-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYV6cqV1I5H6D2pOncq1ETBGkOEOdAzs',
    appId: '1:761898792675:ios:c41e0bc2a1d7c269db77d6',
    messagingSenderId: '761898792675',
    projectId: 'flavor-sample-app-prod',
    storageBucket: 'flavor-sample-app-prod.firebasestorage.app',
    iosBundleId: 'com.example.flavorSampleApp',
  );
}
