// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9aXyaT5zEdkleyXjCy15-qaww4GSj9NM',
    appId: '1:650206124134:web:7de76c75b0e5c90a7275a7',
    messagingSenderId: '650206124134',
    projectId: 'flavor-sample-app-dev',
    authDomain: 'flavor-sample-app-dev.firebaseapp.com',
    storageBucket: 'flavor-sample-app-dev.firebasestorage.app',
    measurementId: 'G-5CT2KVYSWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4GFy483HYhHCvbfipfpEk8Pk0orUrA0k',
    appId: '1:650206124134:android:a7c2711cd0968a277275a7',
    messagingSenderId: '650206124134',
    projectId: 'flavor-sample-app-dev',
    storageBucket: 'flavor-sample-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIiRXoPxM74x-EyE42PZvJPbdOhvt-9VE',
    appId: '1:650206124134:ios:0fab55e16301a0e37275a7',
    messagingSenderId: '650206124134',
    projectId: 'flavor-sample-app-dev',
    storageBucket: 'flavor-sample-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.flavorSampleApp.dev',
  );
}
